version: 2

jobs:
  linux:
    docker:
      - image: swift:4.0
    steps:
      - run: eval "$(curl -sL https://apt.vapor.sh)"
      - run: apt-get install ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift test

  macOS:
    macos:
      xcode: "9.0"
    steps:
      - run: sudo gem install xcpretty
      - run: brew update
      - run: brew tap vapor/tap
      - run: brew install ctls
      - checkout
      - run: swift build
      - run: swift build -c release
      - run: swift package generate-xcodeproj
      - run: xcodebuild -scheme SwiftyBeaverProvider-Package -enableCodeCoverage YES test | xcpretty
      - run: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2
  linux:
    jobs:
      - linux
  macOS:
    jobs:
      - macOS